#ifndef __classid__
#define __classid__

//app-defined descendents of the "Object" class need a unique "class ID"...

const IDNote=           __firstUserClass + 0;
const IDNoteSet=        __firstUserClass + 1;
const IDCat=            __firstUserClass + 2;
const IDCatList=        __firstUserClass + 3;
const IDCatTree=        __firstUserClass + 4;
const IDVisiCat=        __firstUserClass + 5;
const IDTime=           __firstUserClass + 6;
const IDInterval=       __firstUserClass + 7;
const IDDuration=       __firstUserClass + 8;
const IDValue=          __firstUserClass + 9;
const IDColor=          __firstUserClass + 10;
const IDSafStr=         __firstUserClass + 11;
const IDInk=            __firstUserClass + 12;
const IDMemNote=        __firstUserClass + 13;
const IDIntervalObj=    __firstUserClass + 14;
const IDAlarm=          __firstUserClass + 15;
const IDAlarmSet=       __firstUserClass + 16;
const IDFilter=         __firstUserClass + 17;
const IDSysState=       __firstUserClass + 18;
const IDHoliday=        __firstUserClass + 19;
const IDFreq=           __firstUserClass + 20;
const IDRptTotal=       __firstUserClass + 21;
const IDMemView=        __firstUserClass + 22;
const IDTimeComplex=    __firstUserClass + 23;

#endif
