//*****************************************************************************
// resource constants
//*****************************************************************************

// -----------------------------------------------------------------------
//
//                          DIALOGS
//
// -----------------------------------------------------------------------
#define IDD_CATMGR                          100
    #define IDD_CATDELLIST                      101
    #define IDD_CATMGRNEW                       102
    #define IDD_CATDELETE                       103
    #define IDD_CATRENAME                       104
    #define IDD_CATDESC                         105
    #define IDD_CATKEYW                         106
    #define IDD_CATMOVE                         107
    #define IDD_CATNAME                         110
    #define IDD_CATMGRNEW_SUBCAT                120
    #define IDD_SHORT_CATNAME                   130

#define IDD_FILEOPEN                        200
    #define IDD_FILENAME                        201
    #define IDD_FILES                           202
    #define IDD_PATH                            203
    #define IDD_DIRS                            204

#define IDD_ABOUT_KEY                       310
#define IDD_ABOUT_HINSCH                    311

#define IDD_CHKGUESS                        400
    #define IDD_CHKSTART                        401
    #define IDD_CHKEND                          402
    #define IDD_CHKDURATION                     403
    #define IDD_CHKCOST                         404
    #define IDD_CHKLIST                         405

#define IDD_SAVEAS                          500
    #define IDD_SAVEFROM                        501
    #define IDD_SAVETO                          502

#define IDD_NOTE                            700
    #define IDD_NOTEMORE                        701
    #define IDD_NOTERECOG                       702
    #define IDD_NOTETEMPLATE                    703
    #define IDD_NOTEDELETE                      704
    #define IDD_NOTEEDIT                        705
    #define IDD_NOTECATMGR                      706
    #define IDD_NOTEWORKELAPSED                 707
    #define IDD_NOTEEND                         708
    #define IDD_NOTEGUESS                       709
    #define IDD_NOTEDONE                        710
    #define IDD_NOTEDURATION                    712
    #define IDD_NOTEVALUE                       713
    #define IDD_NOTECLEAR                       714
    #define IDD_NOTELIST                        715
    #define IDD_NOTERED                         716
    #define IDD_NOTEREDGRAY                     717
    #define IDD_NOTEGRAY                        718
    #define IDD_NOTEBLUEGRAY                    719
    #define IDD_NOTEBLUE                        720
    #define IDD_MOREBOX                         721
    #define IDD_NOTEFREQ                        728
    #define IDD_FREQTEXT                        729
    #define IDD_RATEUNITS                       732
    #define IDD_NOTEUNITS                       733
    #define IDD_FREQSTATIC                      734
    #define IDD_NOTEINK                         735
    #define IDD_RATE_TITLE                      736
    #define IDD_STARTPICK                       737
    #define IDD_STARTNOW                        738
    #define IDD_AMOUNT_TITLE                    739
    #define IDD_ENDNOW                          740
    #define IDD_NOTERATE                        741
    #define IDD_ALARM_BUTTON                    742
    #define IDD_ALARM_ICON                      743
    #define IDD_NOTECATTITLE                    744
    #define IDD_NOTEDURATION_SCROLL             750
    #define IDD_751                             751
    #define IDD_NOTEMARK                        752
    #define IDD_NOTE_START_DATE                 760
    #define IDD_NOTE_START_TIME                 761
    #define IDD_NOTE_ADDRESS                    770
    #define IDD_NOTE_START_TIME_TITLE           780


#define IDD_CATNEW                          800
    #define IDD_CATNEWNAME                      801
    #define IDD_CATNEWKEY                       802
    #define IDD_CATNEWDESC                      803
    #define IDD_SHORT_NEWCATNAME                805

#define IDD_FILTER                       1200
    #define IDC_FILTER_TEXT                     100
    #define IDC_FILTER_CAT_GROUP                101
    #define IDC_FILTER_CAT_ANY                  102
    #define IDC_FILTER_CAT_ALL                  103
    #define IDC_FILTER_CLEAR_ALL                107
    #define IDC_FILTER_LIST                     108
    #define IDC_FILTER_RED                      109
    #define IDC_FILTER_RED_GRAY                 110
    #define IDC_FILTER_GRAY                     111
    #define IDC_FILTER_BLUE_GRAY                112
    #define IDC_FILTER_BLUE                     113
    #define IDC_FILTER_UNDATED                  114
    #define IDC_FILTER_MILESTONE                115
    #define IDC_FILTER_TASK                     116
    #define IDC_FILTER_FLOAT                    117
    #define IDC_FILTER_DONE                     118
    #define IDC_FILTER_UNDONE                   119
    #define IDC_FILTER_ALARM                    120
    #define IDC_FILTER_NOALARM                  121
    #define IDC_FILTER_FREQ                     122
    #define IDC_FILTER_NOFREQ                   123
    #define IDC_FILTER_BEFORE                   104
    #define IDC_FILTER_AFTER                    105
    #define IDC_FILTER_EXC_GROUP                150
    #define IDC_FILTER_ANY_DATE                 1210
    #define IDC_FILTER_DAY                      1240
    #define IDC_FILTER_WEEK                     1250
    #define IDC_FILTER_MONTH                    1260
    #define IDC_FILTER_DATE                     1270
    #define IDC_FILTER_DATE_GROUP               1280

#define IDD_CALMONTH                        1318
    #define IDD_CALMONGRID                      1319
    #define IDD_CALMINUS                        1320
    #define IDD_CALMINUS2                       1321
    #define IDD_CALPLUS                         1322
    #define IDD_CALPLUS2                        1323
    #define IDD_CALTITLE                        1324

#define IDD_DURATION                        1400

#define IDD_REPORT_OPTIONS                  1450
    #define IDC_REPORT_COL1                     100
    #define IDC_REPORT_COL2                     101
    #define IDC_REPORT_COL3                     102
    #define IDC_REPORT_COL4                     103
    #define IDC_REPORT_COL5                     104
    #define IDC_REPORT_COL6                     105
    #define IDC_REPORT_COL7                     106
    #define IDC_REPORT_COL8                     107
    #define IDC_REPORT_COL9                     108
    #define IDC_REPORT_COL10                    109
    #define IDC_REPORT_COL11                    110

#define IDD_1600                            1600

#define IDD_ORPHAN                          1700

#define IDD_ENTERTIME                       1800
    #define IDD_ENTERTEXT                       1801
    #define IDD_ENTERTIME2                      1850


#define IDD_FREQUENCY	                    2010
	#define IDD_MONTH_1			                2011
	#define IDD_MONTH_2			                2012
	#define IDD_MONTH_3			                2013
	#define IDD_MONTH_4			                2014
	#define IDD_MONTH_5			                2015
	#define IDD_MONTH_6			                2016
	#define IDD_FREQUENCY_VALUE	                2025
	#define IDD_MONTH_1_NAME	                2031
	#define IDD_MONTH_2_NAME	                2032
	#define IDD_MONTH_3_NAME	                2033
	#define IDD_MONTH_4_NAME	                2034
	#define IDD_MONTH_5_NAME	                2035
	#define IDD_MONTH_6_NAME	                2036
    #define IDD_FREQ_PROMPT                     2050
    #define IDD_FREQ_SCROLL                     2060
    #define IDD_FREQ_START                      2070
    #define IDD_FREQ_END                        2080

#define IDD_TIMEPICKER                      3000
    #define IDD_MONTH_PICKER                    3010
    #define IDD_TIMEPICKER_LINE_1               3011
    #define IDD_TIMEPICKER_LINE_2               3012
    #define IDD_TIMEPICKER_UNITS                3013
    #define IDD_TIMEPICKER_DURATION             3016
    #define IDD_TIMEPICKER_TICKER               3019
    #define IDD_TIMEPICKER_EARLIER              3022
    #define IDD_TIMEPICKER_LATER                3025
    #define IDD_TIMEPICKER_DURATION_TEXT        3028
    #define IDD_TIMEPICKER_START_TEXT           3031
    #define IDD_TIMEPICKER_END_TEXT             3034
    #define IDD_TIMEPICKER_USE_DURATION         3035
    #define IDD_TIMEPICKER_USE_TIMES            3036
    #define IDD_TIMEPICKER_GROUP                3037
    #define IDD_TIMEPICKER_TIME                 3050
    #define IDD_TIMEPICKER_TIME_GROUP           3051
    #define IDD_TIMEPICKER_START_TITLE          3052
    #define IDD_TIMEPICKER_END_TITLE            3053
    #define IDD_TIMEPICKER_START_GROUP          3055
    #define IDD_TIMEPICKER_END_GROUP            3056
    #define IDD_TIMEPICKER_NOW                  3080
    #define IDD_TIMEPICKER_DURATION_TITLE       3081
    #define IDD_TIMEPICKER_MILESTONE            3082
    #define IDD_TIMEPICKER_NO_TIME              3083
    #define IDD_TIMEPICKER_ITEMCTL              3084
    #define IDD_TIMEPICKER_TASKCTL              3085
    #define IDD_TIMEPICKER_FLOATCTL             3086
    #define IDD_TIMEPICKER_MILESTONECTL         3087
    #define IDD_TIMEPICKER_WORK_TIME            3090
    #define IDD_TIMEPICKER_WORK_TIME_TITLE      3091

#define IDD_NOTELIST_DIALOG                 3200
    #define IDD_NOTELIST_SELECTOR               3210
    #define IDD_NOTELIST_PROMPT                 3220

#define IDD_MEMORIZED_DIALOG                3300
    #define IDD_MEMORIZED_SELECTOR              3310
    #define IDD_MEMORIZED_DELETE                3320

#define IDD_PREFERENCE                      3550
    #define IDC_DSPGROUP                        100
    #define IDC_DSPNORMAL                       101
    #define IDC_DSPLCD                          102
    #define IDC_DSPWINCOLOR                     103
    #define IDC_AUTOLOAD                        104
    #define IDC_SHOWTIPS                        105
    #define IDC_TIMECONF_GROUP                  106
    #define IDC_TIMECONF_NEVER                  107
    #define IDC_TIMECONF_CAT                    108
    #define IDC_TIMECONF_ALWAYS                 109

#define IDD_ADDRESS                         3600
    #define IDD_ADD_ADD_BUTTON                  10
    #define IDD_ADD_DEL_BUTTON                  20
    #define IDD_ADD_NEXT_BUTTON                 22
    #define IDD_ADD_LAST_BUTTON                 23
    #define IDD_ADD_COUNT                       35
    //#define IDD_ADD_ENTER_NAME                  36
    #define IDD_ADD_DELETE                      37
    #define IDD_ADD_PRINT                       38
    #define IDD_ADD_CLPBRD                      39
    #define IDD_ADD_FIRST_DATA_FIELD            40
    // NB data field ids extend from above to +29
    #define IDD_ADD_SEARCH_FIELD                70
    #define IDD_ADD_FIND                        71
    #define IDD_ADD_IMPORT                      72
    #define IDD_ADD_EXPORT                      73
    #define IDD_ADD_NEW_NOTE                    74
    #define IDD_ADD_DIAL                        75
    #define IDD_ADD_MARK                        76
    #define IDD_ADD_UNMARK_ALL                  77
    #define IDD_ADD_MARK_MATCHES                78
    #define IDD_ADD_NEXT_MARKED                 79
    #define IDD_ADD_ADDR_BUS                    80
    #define IDD_ADD_ADDR_HOME                   81
    #define IDD_ADD_ADDR_ALT                    82
    #define IDD_ADD_A_TO_Z                      83
    // NB a to z buttons extend from above to +25


#define IDD_DAYVIEW                         3700
    #define IDD_DAYVIEW_GROUP_BOX               3710
    #define IDD_DAYVIEW_5_MIN                   3720
    #define IDD_DAYVIEW_6_MIN                   3721
    #define IDD_DAYVIEW_10_MIN                  3722
    #define IDD_DAYVIEW_12_MIN                  3723
    #define IDD_DAYVIEW_15_MIN                  3724
    #define IDD_DAYVIEW_20_MIN                  3725
    #define IDD_DAYVIEW_30_MIN                  3726
    #define IDD_DAYVIEW_60_MIN                  3727
    #define IDD_DAYVIEW_120_MIN                 3728

#define IDD_ADDR_PRTDLG                     3796
#define IDD_HV_PRTDLG                       3797
#define IDD_H_PRTDLG                        3798
#define IDD_V_PRTDLG                        3799
#define IDD_PRTDLG                          3800
    #define IDD_PRTSETUP                        3801
    #define IDD_PRTTITLE                        3802
    #define IDD_PRTNAME                         3803
    #define IDD_PRTGROUP                        3807
    #define IDD_PRTHORZPAGENUM                  3812
    #define IDD_PRTVERTPAGENUM                  3813
    #define IDD_PRTORIENT                       3814
    #define IDD_PRTSTART_H                      3819
    #define IDD_PRTEND_H                        3820
    #define IDD_PRTSTARTSPIN_H                  3821
    #define IDD_PRTENDSPIN_H                    3822
    #define IDD_PRTSTART_V                      3823
    #define IDD_PRTEND_V                        3824
    #define IDD_PRTSTARTSPIN_V                  3825
    #define IDD_PRTENDSPIN_V                    3826
    #define IDD_PRTSHOWPAGE                     3827
    #define IDD_PRTSHOWDATE                     3828
    #define IDD_PRTMARKEDONLY                   3829

#define IDD_PRTSTATUS                       3850
    #define IDD_PRTSTATUSMSG                    3851

#define IDD_CONVERSION                      3900
    #define IDD_TABVIEW_GROUP_BOX_1             4010
    #define IDD_TABVIEW_GROUP_BOX               4010
    #define IDD_TABVIEW_MIX                     4011
    #define IDD_TABVIEW_DECIMAL                 4012
    #define IDD_TABVIEW_HOURS                   4020
    #define IDD_TABVIEW_DAYS                    4030
    #define IDD_TABVIEW_WEEKS                   4040
    #define IDD_TABVIEW_GROUP_BOX_2             4050

#define IDD_ARCHIVE_SAVE                    4400
    #define IDD_ARCHIVE_DELETE                  4410

#define IDD_EXPORT                          4500
    #define IDD_EXPORT_HEADLINES                4510
    #define IDD_EXPORT_FULLTEXT                 4511
    #define IDD_EXPORT_GROUP                    4512
    #define IDD_EXPORT_FIELD_ORDER              4520
    #define IDD_EXPORT_MARKED_ADDR_ONLY         4521

#define IDD_ORDER                           4700
    #define IDD_ORDER_GROUP_1                   100
    #define IDD_ORDER_COLOR_1                   101
    #define IDD_ORDER_DATE_1                    102
    #define IDD_ORDER_DURATION_1                103
    #define IDD_ORDER_TYPE_1                    104
    #define IDD_ORDER_ALPHA_1                   105

    #define IDD_ORDER_GROUP_2                   120
    #define IDD_ORDER_COLOR_2                   121
    #define IDD_ORDER_DATE_2                    122
    #define IDD_ORDER_DURATION_2                123
    #define IDD_ORDER_TYPE_2                    124
    #define IDD_ORDER_ALPHA_2                   125

    #define IDD_ORDER_GROUP_3                   140
    #define IDD_ORDER_COLOR_3                   141
    #define IDD_ORDER_DATE_3                    142
    #define IDD_ORDER_DURATION_3                143
    #define IDD_ORDER_TYPE_3                    144
    #define IDD_ORDER_ALPHA_3                   145

    #define IDC_SET_DEFAULT                     146
    #define IDC_USE_DEFAULT                     147

#define IDD_CSV_ERROR                       4800
    #define IDD_CSV_TEXT                        4810
    #define IDD_CSV_SKIP                        4820
    #define IDD_CSV_CONTINUE                    4830

#define IDD_TIME_CONFLICT                   4900

#define IDD_ALARM                           5100
    #define IDD_ALARM_TEXT                      5110
    #define IDD_ALARM_SCROLL                    5120
    #define IDD_ALARM_UNITS                     5130
    #define IDD_ALARM_ON                        5140

#define IDD_DRAGWIN                         5200

#define IDD_DRAGWIN_WITH_MESSAGE            5201
    #define IDD_DRAGWIN_START                   5210
    #define IDD_DRAGWIN_END                     5220
    #define IDD_DRAGWIN_DURATION                5230
    #define IDD_DRAGWIN_MESSAGE                 5240


#define IDD_TIPMSGWIN                       5300
    #define IDD_TIPMSGTEXT                      5310

#define IDD_HOLIDAY                         5400
    #define IDD_HOLIDAY_COUNTRY                 5410
    #define IDD_HOLIDAY_MONTH_1                 5411
    #define IDD_HOLIDAY_MONTH_2                 5412
    #define IDD_HOLIDAY_MONTH_3                 5413
    #define IDD_HOLIDAY_MONTH_4                 5414
    #define IDD_HOLIDAY_MONTH_5                 5415
    #define IDD_HOLIDAY_MONTH_6                 5416
    #define IDD_HOLIDAY_PROMPT                  5420
    #define IDD_HOLIDAY_MONTH_1_NAME            5431
    #define IDD_HOLIDAY_MONTH_2_NAME            5432
    #define IDD_HOLIDAY_MONTH_3_NAME            5433
    #define IDD_HOLIDAY_MONTH_4_NAME            5434
    #define IDD_HOLIDAY_MONTH_5_NAME            5435
    #define IDD_HOLIDAY_MONTH_6_NAME            5436
    #define IDD_HOLIDAY_SCROLL                  5460

#define IDD_ADD_HOLIDAY                     5600
    #define IDD_NEW_HOLIDAY_NAME                5610

#define IDD_WORK_TIME                       5700
    #define IDD_CONVERSION_GROUP_1              3903
    #define IDD_CONVERSION_GROUP_2              3906
    #define IDD_CONVERSION_DEFAULT_1            3910
    #define IDD_CONVERSION_DEFAULT_2            3920
    #define IDD_CONVERSION_EDIT_1               3970
    #define IDD_CONVERSION_EDIT_2               3980
    #define IDD_SUNDAY	                        4051
    #define IDD_MONDAY	                        4052
    #define IDD_TUESDAY	                        4053
    #define IDD_WEDNESDAY	                    4054
    #define IDD_THURSDAY	                    4055
    #define IDD_FRIDAY	                        4056
    #define IDD_SATURDAY	                    4057
    #define IDD_WORK_DAY_STARTS                 5710
    #define IDD_WORK_DAY_STARTS_AT_9            5720

#define IDD_ALARM_RINGS                     5800
    #define IDD_ALARM_NOTE                      5810
    #define IDD_ALARM_NOTE_TIME                 5820
    #define IDD_ALARM_TIME_NOW                  5830
    #define IDD_ALARM_SNOOZE                    5840
    #define IDD_ALARM_SHOW_NOTE                 5850

#define IDD_OK_CANCEL	                    5900
    #define IDD_MESSAGE	                        5910

#define IDD_OK	                            6000

#define IDD_YES_NO_CANCEL	                6100
#define IDD_MWF_TTH                         6150

#define IDD_CALMON_MONTHS	                6200
    #define IDD_CALMON_JAN	                    6210
    #define IDD_CALMON_FEB	                    6220
    #define IDD_CALMON_MAR	                    6230
    #define IDD_CALMON_APR	                    6240
    #define IDD_CALMON_MAY	                    6250
    #define IDD_CALMON_JUN	                    6260
    #define IDD_CALMON_JUL	                    6270
    #define IDD_CALMON_AUG	                    6280
    #define IDD_CALMON_SEP	                    6290
    #define IDD_CALMON_OCT	                    6300
    #define IDD_CALMON_NOV	                    6310
    #define IDD_CALMON_DEC	                    6320

#define IDD_GROUPCAT                        6400
    #define IDD_GROUPCAT_CATBOX                 6410
    #define IDD_GROUPCAT_AUTOMATIC              6420
    #define IDD_GROUPCAT_NO_GROUPING            6430
    #define IDD_GROUPCAT_SELECTED               6440
    #define IDD_GROUPCAT_GROUP                  6414
    #define IDD_GROUPCAT_SUBTOTALS              6415

#define IDD_NEW_DIALOG                      6500
    #define IDD_NEW_DIALOG_GROUP                6510
    #define IDD_NEW_DIALOG_EMPTY                6520
    #define IDD_NEW_DIALOG_COPY                 6530
    #define IDD_NEW_DIALOG_MORE_GROUP           6550

#define IDD_EXPORT_MAP                      6600
#define IDD_EXPORT_ADDR_MAP                 6601
    #define IDD_EXPORT_MAP_SOURCE               6610
    #define IDD_EXPORT_MAP_TARGET               6620
    #define IDD_EXPORT_MAP_ADD                  6630
    #define IDD_EXPORT_MAP_REMOVE               6640
    #define IDD_EXPORT_MAP_CLEAR                6650
    #define IDD_EXPORT_MAP_DEFAULT              6660

#define IDD_POP_UP_WINDOW                   6700
    #define IDD_POP_UP_TEXT                     6710

#define IDD_DIAL                            6800
    #define IDD_DIAL_PHONE                      6810
    #define IDD_DIAL_TEXT                       6815
    #define IDD_DIAL_SETUP                      6820
    #define IDD_DIAL_ACCESS                     6830
    #define IDD_DIAL_DIAL                       6840
    #define IDD_DIAL_START                      6850
    #define IDD_DIAL_COPY                       6860
    #define IDD_DIAL_NAME                       6870
    #define IDD_DIAL_START_TIME                 6880
    #define IDD_DIAL_DURATION                   6890

#define IDD_DIALSETUP	                    6900
    #define IDD_DIALSETUP_BAUD	                6910
    #define IDD_DIALSETUP_PORT	                6920
    #define IDD_DIALSETUP_GROUP                 6925
    #define IDD_DIALSETUP_PULSE	                6930
    #define IDD_DIALSETUP_TONE	                6940
    #define IDD_DIALSETUP_LOCAL_PRE	            6950
    #define IDD_DIALSETUP_LOCAL_POST	        6960
    #define IDD_DIALSETUP_INTL_PRE	            6970
    #define IDD_DIALSETUP_INTL_POST	            6975
    #define IDD_DIALSETUP_LONG_PRE	            6980
    #define IDD_DIALSETUP_LONG_POST	            6990
    #define IDD_DIALSETUP_ALT_PRE	            6995
    #define IDD_DIALSETUP_ALT_POST	            6996
    #define IDD_DIALSETUP_AREA_CODE	            6998

#define IDD_IMPORT                          7000
    #define IDD_IMPORT_FIELD_MAP                7010

#define IDD_EXPORT_ADDRESS                  7100

#define IDD_IMPORT_MAP                      7200
#define IDD_IMPORT_ADDR_MAP                 7201
    #define IDD_IMPORT_MAP_SOURCE               7220
    #define IDD_IMPORT_MAP_TARGET               7230
    #define IDD_IMPORT_MAP_ADD                  7240
    #define IDD_IMPORT_MAP_REMOVE               7250

#define IDD_INPUT                           7300
    #define IDC_PROMPT                          100
    #define IDC_INPUT                           101

//*****************************************************************************

// -----------------------------------------------------------------------
//
//                          menus and accelerators
//
// -----------------------------------------------------------------------

#define IDM_FRAMEMENU                          25
#define IDM_ACCELERATORS                       50


// -----------------------------------------------------------------------
//
//                          main menu commands
//
// -----------------------------------------------------------------------

//file menu
#define IDM_FILENEW                            51
#define IDM_FILEOPEN                           52
#define IDM_FILESAVE                           53
#define IDM_FILESAVEAS                         54
#define IDM_FILEPRINT                          55
#define IDM_FILESETUP                          56
#define IDM_FILEMERGE                          57
#define IDM_FILEARCHIVE                        58
#define IDM_FILEIMPORT                         59
#define IDM_FILEEXPORT                         60
#define IDM_FILEEXIT                           61
#define IDM_FILEFILE1                          62
#define IDM_FILEFILE2                          63
#define IDM_FILEFILE3                          64
#define IDM_FILEFILE4                          65

//edit menu
#define IDM_EDITPASTE                          75

//note menu
#define IDM_NOTENEW                            100

//folder menu
#define IDM_CATMGR                             125
#define IDM_CATADDR                            126
#define IDM_CATSELECTALL                       127
#define IDM_CATSELECTNONE                      128
#define IDM_CATFILTER                          129

//view menu
#define IDM_VIEWGRAF                           150
#define IDM_VIEWCALENDAR                       151
#define IDM_VIEWTABLE                          152
#define IDM_VIEWTIMELINE                       153
#define IDM_VIEWBROWSER                        154
#define IDM_VIEWHEADLINES                      155
#define IDM_SHOWBARS                           156
#define IDM_VIEWDAY                            157
#define IDM_VIEWWEEK                           158
#define IDM_VIEWMONTH                          159
#define IDM_VIEWYEAR                           160
#define IDM_VIEWTODAY                          161
#define IDM_MEMORIZED_VIEWS                    162
#define IDM_MEMORIZE_VIEW                      163
#define IDM_VIEWMAX                            164
#define IDM_FILE_VIEW_0                        165
#define IDM_FILE_VIEW_1                        166
#define IDM_FILE_VIEW_2                        167
#define IDM_FILE_VIEW_3                        168
#define IDM_FILE_VIEW_4                        169
#define IDM_FILE_VIEW_5                        170
#define IDM_FILE_VIEW_6                        171
#define IDM_FILE_VIEW_7                        172
#define IDM_FILE_VIEW_8                        173
#define IDM_FILE_VIEW_9                        174

//phone menu
#define IDM_PHONEMENU                          199
#define IDM_PHONE_SETUP                        200
#define IDM_PHONE_HANGUP                       201

//option menu
#define IDM_OPTIONFONT                         225
#define IDM_OPTION_WORK_TIME                   226
#define IDM_OPTION_PREFER                      227
#define IDM_OPTION_DURFMT                      228
#define IDM_OPTION_DAYVIEW                     229
#define IDM_OPTION_CONVERSIONS                 230
#define IDM_OPTION_TABVIEW                     231
#define IDM_SORT_ORDER                         232
#define IDM_SORTNOW                            233
#define IDM_OPTION_REPORT                      234
#define IDM_GROUP_CATS                         235
#define IDM_HOLIDAYS                           236
#define IDM_OPTION_RESTORE                     237
#define IDM_OPTION_RESTORE_INTERVAL            238
#define IDM_OPTION_RESTORE_COLUMNS             239
#define IDM_OPTION_RESTORE_TABS                240
#define IDM_OPTION_RESTORE_SORT                241

//help menu
#define IDM_HELPINDEX                          250
#define IDM_HELPABOUT                          251
#define IDM_HELPONHELP                         252
#define IDM_HELPVIEW                           253


// -----------------------------------------------------------------------
//
//                          popup menu commands
//
// -----------------------------------------------------------------------

// timeline popup menu
#define IDM_TIMELINE_POPUP	                   200
    #define IDM_SCROLL_TO_NOTE	               201
    #define IDM_CONVERT_TO_TASK	               202
    #define IDM_CONVERT_TO_MILESTONE	       203
    #define IDM_MOVE_NOTE_HERE                 204

// note popup menu
#define IDM_NOTE_POPUP                         300
    #define IDM_POPDONE                        301
    #define IDM_POPUNDONE                      302
    #define IDM_POPCUT                         303
    #define IDM_POPCOPY                        304
    #define IDM_POPPASTE                       305
    #define IDM_POPCOLOR                       306
    #define IDM_POPDELETE                      307
    #define IDM_POPBLUE                        308
    #define IDM_POPBLUEGRAY                    309
    #define IDM_POPGRAY                        310
    #define IDM_POPREDGRAY                     311
    #define IDM_POPRED                         312
    #define IDM_NOTE_VIEW                      320

// frequency dialog popup menu
#define IDM_FREQUENCY                          400
    #define IDM_FIRSTDATE                      401
    #define IDM_SECONDDATE                     402
    #define IDM_LASTDATE                       403
    #define IDM_EXCLUDEDATE                    404
    #define IDM_ADDDATE                        405
    #define IDM_DELETE_ADDED	               406
    #define IDM_RESTORE_EXCLUDED	           407
    #define IDM_REMOVE_LAST_DATE               408

//catbox, over a folder name
#define IDM_CATBOX_F                             500
    #define IDM_CATBOX_CATEGORY                    501
    #define IDM_CATBOX_DELETE                      503
    #define IDM_CATBOX_NEW_FOLDER                  504
    #define IDM_CATBOX_NEW_SUBFOLDER               505

//catbox, over an address
#define IDM_CATBOX_A                             550
    #define IDM_CATBOX_ADDRESS                     551
    #define IDM_CATBOX_NEW_NOTE                    552
    #define IDM_CATBOX_DIAL                        553

#define IDM_MONTH                              600
    #define IDM_MONTH_ZOOM                         610
    #define IDM_MONTH_NOTES                        620


// -----------------------------------------------------------------------
//
//                               cursors
//
// -----------------------------------------------------------------------

#define IDC_CATSEL                             10000
#define IDC_OUTLINE                            10001
#define IDC_DATESEL                            10002
#define IDC_NOTESEL                            10003
#define IDC_ZOOM                               10004
#define IDC_NOTEBAR                            10005
#define IDC_LONGNOTEBAR                        10006
#define IDC_DRAG_HORIZ                         10010
#define IDC_GROW_LEFT                          10012
#define IDC_GROW_RIGHT                         10014
#define IDC_GROW_UP                            10016
#define IDC_GROW_DOWN                          10018
#define IDC_DRAG_VERT                          10020
#define IDC_DRAG_BOTH                          10022
#define IDC_NO_DRAG                            10024
#define IDC_TIME_MOVE	                       10030
#define IDC_NEW_NOTE	                       10032


// -----------------------------------------------------------------------
//
//                               icons
//
// -----------------------------------------------------------------------

#define ICN_PIMSTER                            1

// -----------------------------------------------------------------------
//
//                               bitmaps
//
// -----------------------------------------------------------------------

#define BMP_STEEL                              5
#define BMP_WHITEGRAY                          6
#define BMP_BLACKGRAY                          7

#define BMP_HICOLOR                            8
#define BMP_LOCOLOR                            9
#define BMP_BLUEGRAY                           10
#define BMP_REDGRAY                            11

#define BMP_PRTPRI1                            12
#define BMP_PRTPRI2                            13
#define BMP_PRTPRI3                            14
#define BMP_PRTPRI4                            15

#define BMP_DRAGSTRIPE                         20
#define BMP_NONWORKDAY                         21
#define BMP_HOLIDAY                            22

// -----------------------------------------------------------------------
//
//                               strings
//
// -----------------------------------------------------------------------


// -----------------------------------------------------------------------
//
//                             buttons in frame (no bitmaps)
//
// -----------------------------------------------------------------------

#define IDD_CATTITLE                           20001
#define IDD_FULLTEXT                           20002
#define IDD_CATSELALL                          20003
#define IDD_CATSELNONE                         20020
#define IDD_BARFILTER                          20004
#define IDD_DATENOW                            20005
#define IDD_BARTITLE                           20006
#define IDD_BARCAT                             20007
#define IDD_TIMETITLE                          20008

#define IDD_SCALEGROUP                      20010
    #define IDD_SCALEHOUR                       20011
    #define IDD_SCALEDAY                        20012
    #define IDD_SCALEWEEK                       20013
    #define IDD_SCALEMONTH                      20014


// -----------------------------------------------------------------------
//
//                             button image offsets
//
// -----------------------------------------------------------------------

#define VGA_LO                                 1000
#define VGA_HI                                 3000
#define VGA_FS                                 5000
#define EGA_LO                                 2000
#define EGA_HI                                 4000
#define EGA_FS                                 6000


// -----------------------------------------------------------------------
//
//                             button bitmaps
//
// -----------------------------------------------------------------------
//
//FIXME some bitmapped buttons, i.e. those in noteview, are not here
#define IDD_BARTABLE                           21001
#define IDD_BARCALENDAR                        21002
#define IDD_BARTIMELINE                        21003
#define IDD_BARNOTE                            21004
#define IDD_BARGRAPH                           21005
#define IDD_FRAMEMAX                           21006
#define IDD_BARBROWSE                          21007
#define IDD_ADDRESS_BUTTON                     21008

//not a button!
#define IDD_BARGROUP                           21009
